### ISSUE TITLE
[PE-D][Tester A] Editing deadline of a task shows a weird behaviour

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-2/tp#165] opened 2022-10-29 03:30 UTC
Inputting `edit_task 1 dl/32-02-2022 2340` does not edit the task and shows an error message, but `edit_task 1 dl/31-02-2022 2340` edits the task deadline to 28-02-2022 2340.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: JonathanWiguna/ped#4

**Comment by jasonqiu212** [comment] 2022-10-29 12:23
Duplicate of #177

**Closed by jasonqiu212** 2022-10-29 12:23 UTC
