### ISSUE TITLE
[PE-D][Tester E] Header quite unintuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-2/tp#174] opened 2022-10-29 04:23 UTC
"All tasks" and "All contacts"  sometimes does not display all tasks, but displays filtered lists

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: thamruicong/ped#5

**Comment by jasonqiu212** [comment] 2022-11-06 02:25
Will fix by changing header names. We feel that this does not go against the feature freeze in v1.4, as the current labels do not accurately describe the list of tasks, and thus is a bug.

**Comment by jasonqiu212** [comment] 2022-11-06 02:27
Duplicate of #157

**Closed by jasonqiu212** 2022-11-06 02:27 UTC
